name: DevSecOps Security Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-pipeline:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      # ---------------------------
      # SAST - Bandit
      # ---------------------------
      - name: Install Bandit
        run: python -m pip install bandit

      - name: Run Bandit Scan
        run: python -m bandit -r . -f json -o bandit-report.json
        continue-on-error: true

      # ---------------------------
      # Build & Run Staging App
      # ---------------------------
      - name: Build Docker Image
        run: docker build -t week3-app ./week3-dast/app

      - name: Stop Old Container
        shell: cmd
        run: |
          docker stop week3-container || exit 0
          docker rm week3-container || exit 0

      - name: Run Application Container
        run: docker run -d --name week3-container -p 5000:5000 week3-app

      # ---------------------------
      # DAST - OWASP ZAP
      # ---------------------------
      - name: Run OWASP ZAP Scan
        shell: powershell
        continue-on-error: true
        run: |
          docker run --rm -t `
          -v "${PWD}:/zap/wrk" `
          ghcr.io/zaproxy/zaproxy:stable `
          zap-full-scan.py `
          -t http://host.docker.internal:5000 `
          -x zap-report.xml

      # ---------------------------
      # Upload to DefectDojo
      # ---------------------------
      - name: Upload Bandit Report
        shell: cmd
        run: |
          curl -X POST -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" -F "engagement=1" -F "scan_type=Bandit Scan" -F "file=@bandit-report.json" http://localhost:8080/api/v2/import-scan/

      - name: Upload ZAP Report
        shell: cmd
        run: |
          curl -X POST -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" -F "engagement=1" -F "scan_type=ZAP Scan" -F "file=@zap-report.xml" http://localhost:8080/api/v2/import-scan/
