name: Week 4 - Reporting & Aggregation

on:
  push:
    branches:
      - week-4

jobs:
  security-pipeline:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      # -----------------------------
      # SAST - Bandit
      # -----------------------------
      - name: Install Bandit
        run: python -m pip install bandit

      - name: Generate Bandit JSON Report
        run: python -m bandit -r week3-dast -f json -o bandit-report.json
        continue-on-error: true

      - name: Verify Bandit Report Exists
        shell: cmd
        run: dir bandit-report.json

      # -----------------------------
      # Build & Run Staging Container
      # -----------------------------
      - name: Build Docker Image
        run: docker build -t week3-app ./week3-dast/app

      - name: Run Application Container
        run: docker run -d --name week3-container -p 5000:5000 week3-app

      # -----------------------------
      # DAST - OWASP ZAP
      # -----------------------------
      - name: Run OWASP ZAP Full Scan (JSON Output)
        shell: powershell
        continue-on-error: true
        run: |
          docker run --rm -t `
          -v "${PWD}:/zap/wrk" `
          ghcr.io/zaproxy/zaproxy:stable `
          zap-full-scan.py `
          -t http://host.docker.internal:5000 `
          -x zap-report.xml


      - name: Verify ZAP Report Exists
        shell: cmd
        run: dir zap-report.json

      - name: Show Bandit JSON Content
        shell: cmd
        run: type bandit-report.json

      - name: Show ZAP JSON Content
        shell: cmd
        run: type zap-report.json

      # -----------------------------
      # Upload SAST Report to DefectDojo
      # -----------------------------
      - name: Upload Bandit Report to DefectDojo
        shell: cmd
        run: |
          curl -X POST -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" -F "engagement=1" -F "scan_type=Bandit scan" -F "file=@bandit-report.json" http://localhost:8080/api/v2/import-scan/

      # -----------------------------
      # Upload DAST Report to DefectDojo
      # -----------------------------
      - name: Upload ZAP Report to DefectDojo
        shell: cmd
        run: |
          curl -X POST -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" -F "engagement=1" -F "scan_type=ZAP Scan" -F "file=@zap-report.xml" http://localhost:8080/api/v2/import-scan/

      # -----------------------------
      # Cleanup
      # -----------------------------
      - name: Stop Application Container
        shell: cmd
        run: |
          docker stop week3-container
          docker rm week3-container
