name: Week 4 - Reporting & Aggregation

on:
  push:
    branches:
      - week-4

jobs:
  security-pipeline:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      # --- SAST ---
      - name: Install Bandit
        run: python -m pip install bandit

      - name: Generate Bandit Report
        run: python -m bandit -r week2-sast-sonarqube -f json -o bandit-report.json

      # --- Build & Run App ---
      - name: Build Docker Image
        run: docker build -t week3-app ./week3-dast/app

      - name: Run Application Container
        run: docker run -d -p 5000:5000 week3-app

      # --- DAST ---
      - name: Run OWASP ZAP Scan
        shell: powershell
        continue-on-error: true
        run: |
          docker run --rm -t `
          -v "${PWD}:/zap/wrk" `
          ghcr.io/zaproxy/zaproxy:stable `
          zap-full-scan.py `
          -t http://host.docker.internal:5000 `
          -r zap-report.html `
          -J zap-report.json

      # --- Upload SAST to DefectDojo ---
      - name: Upload Bandit Report
        shell: powershell
        run: |
          Invoke-RestMethod -Method Post `
          -Uri "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" `
          -Headers @{ "Authorization" = "Token ${{ secrets.DEFECTDOJO_API_KEY }}" } `
          -Form @{
            "engagement" = "3"
            "scan_type" = "Bandit Scan"
            "file" = Get-Item "bandit-report.json"
          }

      # --- Upload DAST to DefectDojo ---
      - name: Upload ZAP Report
        shell: powershell
        run: |
          Invoke-RestMethod -Method Post `
          -Uri "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" `
          -Headers @{ "Authorization" = "Token ${{ secrets.DEFECTDOJO_API_KEY }}" } `
          -Form @{
            "engagement" = "1"
            "scan_type" = "ZAP Scan"
            "file" = Get-Item "zap-report.json"
          }
